name: 1234

on:
  push:
    branches:
      - main
  schedule:
    - cron: '29-59 7 * * *'  # Runs every minute from 07:00 to 07:59 UTC
  workflow_dispatch:  # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Running
      run: |
        echo "Hello - $(date -u)"
